### ISSUE TITLE
Support non-root user

### ISSUE THREAD

**Issue by frozenbonito** [aquaproj/devcontainer-features#14]
### Feature Overview

Support non-root user which is the default for common dev container images.

### Why is the feature needed?

Generally, a non-root user is used in the dev container.
For example, the default user for many of the images provided by [devcontainers/images](https://github.com/devcontainers/images) is `vscode`.

However, this feature doesn't seems to support non-root user.
By default, `aqua` is installed in a path that is not available to non-root user (`/root/.local/share/aquaproj-aqua/bin`).
The installation path can be changed with environment variable `AQUA_ROOT_DIR`, but in any case, `aqua i` by non-root user will fail with permission denied because `aqua` is installed by the root user.

### Example Code

Configuration (`devcontainer.json`)

```json
{
  "name": "Go",
  "image": "mcr.microsoft.com/devcontainers/go:1-1.22-bookworm",
  "features": {
    "ghcr.io/aquaproj/devcontainer-features/aqua-installer:0.1.0": {
      "aqua_version": "v2.27.0"
    }
  },
  "remoteEnv": {
    "PATH": "/home/vscode/.local/share/aquaproj-aqua/bin:${containerEnv:PATH}"
  }
}
```

Once the dev container is built, aqua is ready to use out of the box for `vscode` user.

**Comment by suzuki-shunsuke** [comment]
Thank you for your report!
I'm working on fixing this issue.

- https://github.com/aquaproj/devcontainer-features/pull/16

**Comment by suzuki-shunsuke** [comment]
0.1.1 is out 🎉
https://github.com/aquaproj/devcontainer-features/releases/tag/feature_aqua-installer_0.1.1
